# Postas da Aplicacao
server:
  port: 8080

spring:

  # Configuracao do postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/estudos_pizzaria_dankicode
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: bh123456

  # JPA e Hibernate
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
